services:
  graph-executor:
    build: .
    container_name: graph-executor
    restart: unless-stopped
    environment:
      - PORT
      - ASSETS_DIR
      - NEO4J_URI
      - NEO4J_DATABASE
      - NEO4J_USER
      - NEO4J_PASSWORD
    networks:
      - proxy

networks:
  proxy:
    external: true
